// flow-typed signature: 25b2131fdec79358dd736d3fefa5d272
// flow-typed version: <<STUB>>/ismobilejs_v0.4.1/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ismobilejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ismobilejs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ismobilejs/Gruntfile' {
  declare module.exports: any;
}

declare module 'ismobilejs/isMobile' {
  declare module.exports: any;
}

declare module 'ismobilejs/isMobile.min' {
  declare module.exports: any;
}

declare module 'ismobilejs/tests/spec/AmazonSpec' {
  declare module.exports: any;
}

declare module 'ismobilejs/tests/spec/AndroidSpec' {
  declare module.exports: any;
}

declare module 'ismobilejs/tests/spec/AppleSpec' {
  declare module.exports: any;
}

declare module 'ismobilejs/tests/spec/DesktopSpec' {
  declare module.exports: any;
}

declare module 'ismobilejs/tests/spec/OtherSpec' {
  declare module.exports: any;
}

declare module 'ismobilejs/tests/spec/SevenInchSpec' {
  declare module.exports: any;
}

declare module 'ismobilejs/tests/spec/WindowsSpec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ismobilejs/Gruntfile.js' {
  declare module.exports: $Exports<'ismobilejs/Gruntfile'>;
}
declare module 'ismobilejs/isMobile.js' {
  declare module.exports: $Exports<'ismobilejs/isMobile'>;
}
declare module 'ismobilejs/isMobile.min.js' {
  declare module.exports: $Exports<'ismobilejs/isMobile.min'>;
}
declare module 'ismobilejs/tests/spec/AmazonSpec.js' {
  declare module.exports: $Exports<'ismobilejs/tests/spec/AmazonSpec'>;
}
declare module 'ismobilejs/tests/spec/AndroidSpec.js' {
  declare module.exports: $Exports<'ismobilejs/tests/spec/AndroidSpec'>;
}
declare module 'ismobilejs/tests/spec/AppleSpec.js' {
  declare module.exports: $Exports<'ismobilejs/tests/spec/AppleSpec'>;
}
declare module 'ismobilejs/tests/spec/DesktopSpec.js' {
  declare module.exports: $Exports<'ismobilejs/tests/spec/DesktopSpec'>;
}
declare module 'ismobilejs/tests/spec/OtherSpec.js' {
  declare module.exports: $Exports<'ismobilejs/tests/spec/OtherSpec'>;
}
declare module 'ismobilejs/tests/spec/SevenInchSpec.js' {
  declare module.exports: $Exports<'ismobilejs/tests/spec/SevenInchSpec'>;
}
declare module 'ismobilejs/tests/spec/WindowsSpec.js' {
  declare module.exports: $Exports<'ismobilejs/tests/spec/WindowsSpec'>;
}
