module.exports = {
	/* Query */
	UPDATE_QUERY_TERM: 'UPDATE_QUERY_TERM',
	CLEAR_QUERY_TERM: 'CLEAR_QUERY_TERM',

	/* Sort */
	CHANGE_SORT: 'CHANGE_SORT',
	
	/* Search */
	REQUEST_SEARCH: 'REQUEST_SEARCH',
	REQUEST_SEARCH_SUCCESS: 'REQUEST_SEARCH_SUCCESS',
	REQUEST_SEARCH_FAILURE: 'REQUEST_SEARCH_FAILURE',

	/* For URL Routing */
	UPDATE_STATE_FROM_QUERY: 'UPDATE_STATE_FROM_QUERY',

	/* Facets */
	ADD_FACET: 'ADD_FACET',
	REMOVE_FACET: 'REMOVE_FACET',
	REMOVE_ALL_FACETS: 'REMOVE_ALL_FACETS',
	REPLACE_FACET: 'REPLACE_FACET',

	/* AutoSuggest */
	UPDATE_QUERY_TERM_AUTOSUGGEST: 'UPDATE_QUERY_TERM_AUTOSUGGEST',
	CLEAR_QUERY_TERM_AUTOSUGGEST: 'CLEAR_QUERY_TERM_AUTOSUGGEST',
	REQUEST_AUTOSUGGEST: 'REQUEST_AUTOSUGGEST',
	REQUEST_AUTOSUGGEST_SUCCESS: 'REQUEST_AUTOSUGGEST_SUCCESS',
	REQUEST_AUTOSUGGEST_FAILURE: 'REQUEST_AUTOSUGGEST_FAILURE',
	OPEN_AUTOSUGGEST: 'OPEN_AUTOSUGGEST',
	CLOSE_AUTOSUGGEST: 'CLOSE_AUTOSUGGEST',
	ADD_FACET_AUTOSUGGEST: 'ADD_FACET_AUTOSUGGEST',

	/* Bookmark */

	ADD_BOOKMARK: 'ADD_BOOKMARK',
	REMOVE_BOOKMARK: 'REMOVE_BOOKMARK',

	/* History */

	ADD_HISTORY: 'ADD_HISTORY',
	CLEAR_HISTORY: 'CLEAR_HISTORY',

	/* Pagination */

	CHANGE_PAGE: 'CHANGE_PAGE',
	CHANGE_PER_PAGE: 'CHANGE_PER_PAGE',

	/* Guide */

	INIT_GUIDE: 'INIT_GUIDE',	
	REQUEST_GUIDE: 'REQUEST_GUIDE',
	REQUEST_GUIDE_SUCCESS: 'REQUEST_GUIDE_SUCCESS',
	REQUEST_GUIDE_FAILURE: 'REQUEST_GUIDE_FAILURE',
	INCREMENT_GUIDE: 'INCREMENT_GUIDE',
	DECREMENT_GUIDE: 'DECREMENT_GUIDE',    
	REPLACE_FACET_GUIDE: 'REPLACE_FACET_GUIDE',
	CLEAR_FACET_AFTER_INDEX: 'CLEAR_FACET_AFTER_INDEX',


	/* Locale */

	SET_LOCALE: 'SET_LOCALE',

	/* Filter */

	ADD_FILTER: 'ADD_FILTER',
	REMOVE_FILTER: 'REMOVE_FILTER',
	CLEAR_FILTERS: 'CLEAR_FILTERS',
}